### ISSUE TITLE
Any plan on service-worker for offline usage?

### ISSUE THREAD

**Issue by JLHwung** [vuejs/vuejs.org#771]
The [hexo-offline](https://github.com/JLHwung/hexo-offline) supports using `sw-precache` to generate a service worker for offline usage on any hexo site.

[Browser Support](https://jakearchibald.github.io/isserviceworkerready/)

**Comment by chrisvfritz** [comment]
As I just [mentioned here](https://github.com/vuejs/vuejs.org/pull/772), I'm definitely not opposed to adding offline support. 👍

**Comment by gogamwar** [comment]
I tried [hexo-offline](https://github.com/JLHwung/hexo-offline) with the following configuration:
```yaml
offline:
  maximumFileSizeToCacheInBytes: 10485760
  staticFileGlobs:
    - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff}
    - public/**/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff}
    - public/manifest.json
    - public/browserconfig.xml
  stripPrefix: public
```
In general, it works, but I was confused by these errors. I also was not able to properly configure caching CDN scripts and Google fonts, it works only through the browser cache.
![Network errors](https://cloud.githubusercontent.com/assets/13474134/23102247/0236665c-f6b7-11e6-86ac-2b604fcf4ea9.png)
